[pytest]
python_files = *_tests.py test_*.py  # Это мы добавили в предыдущем шаге
python_classes = Test*               # Устанавливает правила для имен классов
python_functions = test_*            # Устанавливает правила для имен функций


markers =
    users: marker for user related tests.
    regression: marker for regression tests.
    authentication: marker for authentication tests.

