[pytest]
addopts = -s -v
python_files = *_tests.py test_*.py
python_classes = Test*               # Устанавливает правила для имен классов
python_functions = test_*            # Устанавливает правила для имен функций


markers =
    users: marker for user related tests.
    files: marker for file related tests.
    regression: marker for regression tests.
    authentication: marker for authentication tests.

